server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # WASM/dll files need this MIME type for Blazor to load them correctly.
    types {
        application/wasm wasm;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
